### PR TITLE
Timeout

### LINKED ISSUE #30: Allow for timeouts when expecting values from channels
In many places, the code waits for information on a channel, but does not allow for a timeout. As this information is provided by other nodes over the network, the information will never come in case of crashes, and the goroutine will be stuck forever.
Allowing for a timeout in a `select` statement will make the code more fault-tolerant.

### PR DESCRIPTION
**Pull request by JoaoAndreSa**
Closes #30 

I added the timeouts for all channels. I've added a default 10min value that can be easily changed at runtime. Is this enough?

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -27,7 +27,7 @@ test_lint:
 	}
 
 test_local:
-	go test -v -race -short -p=1 ./...
+	go test -v -short -p=1 ./...
```
Comment (ineiti) [inline Makefile]: That's a dangerous change! You should be more concerned to change the tests so that they don't time-out. The `-race` saved us on numerous occasions, so if you decide to _really_ go without it, I'd make sure that the other members of the team are OK with it.

File: protocols/shuffling_protocol.go [hunk 2]
```diff
@@ -116,6 +118,10 @@ func NewShufflingProtocol(n *onet.TreeNodeInstance) (onet.ProtocolInstance, erro
 			break
 		}
 	}
+
+	// default timeout
+	dsp.Timeout = 10 * time.Minute
```
Comment (ineiti) [inline protocols/shuffling_protocol.go]: How has this timeout been chosen?

Why are there different timeouts?

Shouldn't it be possible to change the timeout, e.g., with an environment variable?

File: Makefile (hunk 1 above)
Comment (JoaoAndreSa) [reply Makefile]: So I removed the race because while I was updating onet i started having this error which only disappeared after removing the -race flag. I'm not sure where is this coming from :/
 
Screenshot 2020-03-11 at 10 04 45

File: protocols/shuffling_protocol.go (hunk 2 above)
Comment (JoaoAndreSa) [reply protocols/shuffling_protocol.go]: There was no rule to chose the timeout. I just chose enough time for it not to fail in normal query scenarios. As for the timeouts I added one for each different protocol or service. This way we can pass it when calling the protocol or service. You think an environment variable would be better?

**Comment by JoaoAndreSa** [comment]
> Looks good to me!
> 
> Minor note: the `break` for [no-op branches](https://github.com/golang/go/wiki/Switch#noop-case) in `select`/`switch` is not necessary (see e.g. https://play.golang.org/p/3kj1htOkqNK), but it does not hurt. :)

Removed `break`

File: Makefile (hunk 1 above)
Comment (JoaoAndreSa) [reply Makefile]: The plot thickens... apparently this only happens locally

Comment (ineiti) [reply Makefile]: I think that is bbolt's error in conjunction with the latest go. Are you already using go 1.14?

@tharvik - what is the state of bbolt and the latest go?

Comment (JoaoAndreSa) [reply Makefile]: yes. If it's the case I can go back to a previous version

File: protocols/shuffling_protocol.go (hunk 2 above)
Comment (ineiti) [reply protocols/shuffling_protocol.go]: It depends (as always):
- do you trust the leader to not send a malicious timeout that will keep your resources? (I suppose yes)
- do you want to have each node decide on his own timeouts? (I suppose no)

So with a yes - no answer, I think you're doing the right thing ;) 

But instead of hardcoding the timeout, I'd use https://golang.org/pkg/os/#Getenv to read the `MEDCO_TIMEOUT` environment variable, and, if it is not set, use a globally defined timeout.

Timeouts are always hard to get right (even @bford said "good luck" when I had to do it ;), so having them easily adjustable also from the outside is a plus!

Comment (JoaoAndreSa) [reply protocols/shuffling_protocol.go]: @ineiti I followed your suggestion and changed the timeouts 3dcc5b4 
Would this be better?

File: protocols/collective_aggregation_protocol.go [hunk 3]
```diff
@@ -201,14 +197,19 @@ func (p *CollectiveAggregationProtocol) Dispatch() error {
 
 // Announce forwarding down the tree.
 func (p *CollectiveAggregationProtocol) aggregationAnnouncementPhase() error {
+	timeout, err := time.ParseDuration(os.Getenv("MEDCO_TIMEOUT"))
```
Comment (ineiti) [inline protocols/collective_aggregation_protocol.go]: It should be enough to put this in a`func init()` at the beginning of the file `constants.go`. Then you can remove it from all the methods you're calling it...

Comment (JoaoAndreSa) [reply protocols/collective_aggregation_protocol.go]: done abbe277

File: lib/constants.go [hunk 4]
```diff
@@ -1,12 +1,20 @@
...
 	"sync"
 	"time"
 
 	"go.dedis.ch/onet/v3/simul/monitor"
 )
 
+func init() {
+	tmp, err := time.ParseDuration(os.Getenv("MEDCO_TIMEOUT"))
+	if err != nil {
+		TIMEOUT = tmp
```
Comment (ineiti) [inline lib/constants.go]: Last comment:
```
if len(os.Getenv("MEDCO_TIMEOUT") > 0 {
  log.Warn("Couldn't parse MEDCO_TIMEOUT")
}
```

Comment (JoaoAndreSa) [reply lib/constants.go]: I've added it in 5564657
However now that I updated to the new onet version 3.1.1 the error with the `"E : overlay.go:613 (v3.(*Overlay).nodeDelete) - Error while closing node: Can't shutdown empty ProtocolInstance:"` pops way more often. Do you know what changed with this new 3.1 version of Onet?

Screenshot 2020-03-11 at 14 42 22

Comment (JoaoAndreSa) [reply lib/constants.go]: It disappears if I remove the error condition when calling `tn.SetConfig()`

File: Makefile (hunk 1 above)
Comment (tharvik) [reply Makefile]: @ineiti bbolt is still broken, we need https://github.com/etcd-io/bbolt/pull/201 before updating onet/cothority (but containerd and kubernetes both waits on that, it will be fixed in a matter of days)

File: protocols/collective_aggregation_protocol.go [hunk 5]
```diff
@@ -195,11 +196,15 @@ func (p *CollectiveAggregationProtocol) Dispatch() error {
 
 // Announce forwarding down the tree.
 func (p *CollectiveAggregationProtocol) aggregationAnnouncementPhase() error {
-	dataReferenceMessage := <-p.DataReferenceChannel
-	if !p.IsLeaf() {
-		if err := p.SendToChildren(&dataReferenceMessage.DataReferenceMessage); err != nil {
-			return errors.New("Error sending <DataReferenceMessage>:" + err.Error())
+	select {
+	case dataReferenceMessage := <-p.DataReferenceChannel:
+		if !p.IsLeaf() {
```
Comment (tharvik) [inline protocols/collective_aggregation_protocol.go]: Unneded if, `SendToChildren` when having none should work.

File: protocols/collective_aggregation_protocol.go [hunk 6]
```diff
@@ -195,11 +196,15 @@ func (p *CollectiveAggregationProtocol) Dispatch() error {
...
+			if err := p.SendToChildren(&dataReferenceMessage.DataReferenceMessage); err != nil {
+				return errors.New("Error sending <DataReferenceMessage>:" + err.Error())
```
Comment (tharvik) [inline protocols/collective_aggregation_protocol.go]: You can use the new `fmt.Errorf` when returning error (it will also keep the stacktrace).

```suggestion
				return fmt.Errorf("Error sending <DataReferenceMessage>: %v", err)
```

File: protocols/shuffling+ddt_protocol.go [hunk 7]
```diff
@@ -152,8 +153,19 @@ func (p *ShufflingPlusDDTProtocol) Start() error {
...
+	case shufflingPlusDDTBytesMessageLength = <-p.LengthNodeChannel:
+	case <-time.After(libunlynx.TIMEOUT):
+		return errors.New(p.ServerIdentity().String() + " didn't get the <shufflingPlusDDTBytesMessageLength> on time.")
+	}
+
+	var tmp shufflingPlusDDTBytesStruct
+	select {
+	case tmp = <-p.PreviousNodeInPathChannel:
+	case <-time.After(libunlynx.TIMEOUT):
+		return errors.New(p.ServerIdentity().String() + " didn't get the <tmp> on time.")
```
Comment (tharvik) [inline protocols/shuffling+ddt_protocol.go]: Maybe a better name than `tmp`?

File: services/service.go [hunk 8]
```diff
@@ -416,13 +416,9 @@ func (s *Service) HandleQueryBroadcastFinished(recq *QueryBroadcastFinished) (ne
 
 // NewProtocol creates a protocol instance executed by all nodes
 func (s *Service) NewProtocol(tn *onet.TreeNodeInstance, conf *onet.GenericConfig) (onet.ProtocolInstance, error) {
-	err := tn.SetConfig(conf)
-	if err != nil {
-		return nil, err
-	}
+	tn.SetConfig(conf)
```
Comment (tharvik) [inline services/service.go]: Don't drop the error.

File: simul/proofs_verification_simul.go [hunk 9]
```diff
@@ -231,23 +231,27 @@ func (sim *ProofsVerificationSimulation) Run(config *onet.SimulationConfig) erro
...
-			return errors.New("shuffling proofs failed")
-		} else if results[5] == false {
-			return errors.New("collective aggregation proofs failed")
+		select {
+		case results := <-root.ProtocolInstance().(*protocolsunlynxutils.ProofsVerificationProtocol).FeedbackChannel:
+			libunlynx.EndTimer(round)
+
+			log.Lvl1(len(results), " proofs verified")
+
+			if results[0] == false {
```
Comment (tharvik) [inline simul/proofs_verification_simul.go]:
```suggestion
			if !results[0] {
```

File: protocols/collective_aggregation_protocol.go (hunk 5 above)
Comment (JoaoAndreSa) [reply protocols/collective_aggregation_protocol.go]: 31c25d5

File: lib/constants.go (hunk 4 above)
Comment (ineiti) [reply lib/constants.go]: Do you have a simple test-case that I can run to trigger it?

And what do you mean by "removing the error condition when calling `tn.SetConfig()`"?

File: protocols/collective_aggregation_protocol.go (hunk 5 above)
Comment (tharvik) [reply protocols/collective_aggregation_protocol.go]: Arf, I misexplained it; the `if !p.IsLeaf()` is unnecessary, as a Leaf sending to it's children is a NOP.
And you're droping the `error` here.

File: protocols/collective_aggregation_protocol.go (hunk 6 above)
Comment (JoaoAndreSa) [reply protocols/collective_aggregation_protocol.go]: switched everywhere to fmt.Errorf: 8861342

File: protocols/collective_aggregation_protocol.go (hunk 5 above)
Comment (JoaoAndreSa) [reply protocols/collective_aggregation_protocol.go]: ahh I did not get it :P 
Ok it's fixed: f3812c3

**Comment by mickmis** [comment]
I agree with @ineiti comment about having it configurable as environment variable. We can that way set it easily in MedCo through the Docker environment.
It should also be documented somewhere, like in the README.md.

**Comment by JoaoAndreSa** [comment]
> Shouldn't be called `DEFAULT_TIMEOUT` rather than `TIMEOUT` ?

Done 5bc1e5d

**Comment by JoaoAndreSa** [comment]
> I agree with @ineiti comment about having it configurable as environment variable. We can that way set it easily in MedCo through the Docker environment.
> It should also be documented somewhere, like in the README.md.

About this I already did. There is this function to set it up based on the environment variable MEDCO_TIMEOUT

```golang
func init() {
	tmp, err := time.ParseDuration(os.Getenv("MEDCO_TIMEOUT"))
	if err == nil {
		DEFAULT_TIMEOUT = tmp
	} else {
		log.Warn("Couldn't parse MEDCO_TIMEOUT, using default value: ", DEFAULT_TIMEOUT.String())
	}
}
```

File: protocols/shuffling+ddt_protocol.go (hunk 7 above)
Comment (JoaoAndreSa) [reply protocols/shuffling+ddt_protocol.go]: I tried to clean a bit these `tmp` variables. I changed this one to `spDDTbs` (referring to the type of the object `shufflingPlusDDTBytesStruct`) even though is not that much better.

a4d36eb

File: simul/proofs_verification_simul.go (hunk 9 above)
Comment (JoaoAndreSa) [reply simul/proofs_verification_simul.go]: changed this everywhere f3812c3

File: services/service.go (hunk 8 above)
Comment (JoaoAndreSa) [reply services/service.go]: If I don't drop the error 7f37465 some tests stop working
e.g. - `^TestServiceClearAttr$` in `github.com/ldsec/unlynx/services `

```
 - couldn't set config: Can't set config twice:
        go.dedis.ch/onet/v3.(*TreeNodeInstance).SetConfig
            /Users/jagomes/Go/pkg/mod/go.dedis.ch/onet/v3@v3.1.1/treenode.go:879:
```

File: lib/constants.go (hunk 4 above)
Comment (JoaoAndreSa) [reply lib/constants.go]: @ineiti  see here https://github.com/ldsec/unlynx/pull/38#discussion_r391641523

File: services/service.go (hunk 8 above)
Comment (tharvik) [reply services/service.go]: That might indicate a bug :P

`Service.NewProtocol` is handled specially by onet, to start new protocol on the children of the root node of the tree. To fix it, move the `SetConfig` in `StartProtocol`, just before calling `NewProtocol`, this way, only root will actually set the config for the whole tree, ensuring that every node get's it before starting.

Comment (JoaoAndreSa) [reply services/service.go]: Ok this is perfect it works like a charm 6340084

File: lib/constants.go (hunk 4 above)
Comment (JoaoAndreSa) [reply lib/constants.go]: fixed https://github.com/ldsec/unlynx/pull/38#discussion_r391672676

File: protocols/shuffling_protocol.go (hunk 2 above)
Comment (ineiti) [reply protocols/shuffling_protocol.go]: yes, looks good to me.

File: services/service.go (hunk 8 above)
Comment (ineiti) [reply services/service.go]: > That might indicate a bug :P
> 
> `Service.NewProtocol` is handled specially by onet, to start new protocol on the children of the root node of the tree. To fix it, move the `SetConfig` in `StartProtocol`, just before calling `NewProtocol`, this way, only root will actually set the config for the whole tree, ensuring that every node get's it before starting.

wow - @tharvik gets an onet expert! I know whom I'll ask for my next bug ;)

File: app/client.go [hunk 10]
```diff
@@ -98,7 +98,7 @@ func parseQuery(el *onet.Roster, sum string, count bool, where, predicate, group
 	whereRegex := "{(w[0-9]+(,\\s*[0-9]+))*(,\\s*w[0-9]+(,\\s*[0-9]+))*}"
 	groupByRegex := "{g[0-9]+(,\\s*g[0-9]+)*}"
 
-	if !checkRegex(sum, sumRegex) {
+	if checkRegex(sum, sumRegex) == false {
```
Comment (ineiti) [inline app/client.go]: ? I thought @tharvik 's suggestion was to change from ` == false` to `!`, no? Anyway, that would be my preference.

**Comment by ineiti** [comment]
Reality check: CoVid-19, people stay at home, no coffee talk, and everybody gathers around @JoaoAndreSa PR to tell him how to code... Sorry guy!

File: app/client.go (hunk 10 above)
Comment (JoaoAndreSa) [reply app/client.go]: you're right I didn't see it correctly :(

Comment (JoaoAndreSa) [reply app/client.go]: done fixed e5509ba

**Comment by JoaoAndreSa** [comment]
I think I addressed all the reviews/suggestions. :) Let me know (@ineiti @tharvik @mickmis @cgrigis) if I forgot something.
